### ISSUE TITLE
Implementation support

### ISSUE THREAD

**Issue by Bibban** [MikaelWahlberg/enegic_hass#1]
Hej,
har försökt hitta Enegic-integration till Home Assistant men det verkar inte finnas något. Vad jag förstår så har Enegic inget öppet API som kan användas.
Snubblade över detta och undrar om det går att använda för att få data från min Enegic monitor till Home assistant.
Dock är jag väldigt ny inom detta och undrar om det är möjligt att få en utförligare instruktion kring implementation?
Tex hur man hittar "ITEM_ID?
Hur sätter man "TOKEN" för app.egenic.com? Genereras inte en ny TOKEN varje gång man loggar in med username/pwd?

**Comment by MikaelWahlberg** [comment]
Man kunde skapa en publik dashboard förut. Men jag hittar inte den funktionen längre, så dom har nog tagit bort möjligheten att utnyttja det.  (Jag använder inte detta själv längre, fick en ny elmätare med P1-port, det var mycket bättre ändå :) )

**Comment by Bibban** [comment]
Tack! Då begriper jag lite mer.
Får väl hoppas att Egenic släpper ett öppet API så att någon kan göra en integration till HA :)
